import { COMMANDS, type VimCommand } from './commands'
import { WORLDS } from '../content/tiers'
import type { Tier } from './types'

/**
 * The downloadable / printable Vim cheatsheet — generated from the SAME command
 * catalog the game teaches (src/game/commands.ts), so it can never drift from
 * the curriculum. Rendered to Markdown (universal, diff-friendly) and to a
 * fully self-contained HTML page (open in a browser → File ▸ Print ▸ Save as PDF).
 */

const CATEGORY_LABEL: Record<string, string> = {
  modes: 'Modes',
  motion: 'Motion',
  edit: 'Edits',
  operator: 'Operators',
  'text-object': 'Text objects',
  ex: 'Ex commands',
  power: 'Power',
}
const CATEGORY_ORDER = ['modes', 'motion', 'edit', 'operator', 'text-object', 'ex', 'power']

export interface CheatSection {
  tier: Tier
  name: string
  subtitle: string
  accent: string
  groups: Array<{ label: string; commands: VimCommand[] }>
}

/** Commands grouped by world (tier), then by category — the cheatsheet spine. */
export function cheatsheetSections(): CheatSection[] {
  return WORLDS.map((w) => {
    const inWorld = COMMANDS.filter((c) => c.tier === w.tier)
    const groups = CATEGORY_ORDER.map((key) => ({
      label: CATEGORY_LABEL[key] ?? key,
      commands: inWorld.filter((c) => c.category === key),
    })).filter((g) => g.commands.length > 0)
    return { tier: w.tier, name: w.name, subtitle: w.subtitle, accent: w.accent, groups }
  }).filter((s) => s.groups.length > 0)
}

/** cheatsheetSections() narrowed to a free-text query over command keys + labels.
 *  Empty groups/sections are dropped so only matching worlds render. */
export function filterCheatsheetSections(query: string): CheatSection[] {
  const q = query.trim().toLowerCase()
  if (!q) return cheatsheetSections()
  return cheatsheetSections()
    .map((s) => ({
      ...s,
      groups: s.groups
        .map((g) => ({ ...g, commands: g.commands.filter((c) => c.keys.toLowerCase().includes(q) || c.label.toLowerCase().includes(q)) }))
        .filter((g) => g.commands.length > 0),
    }))
    .filter((s) => s.groups.length > 0)
}

const SITE = 'https://github.com/Zeecka/VimLegends'
const TAGLINE = 'Learn Vim by playing — real editor, real keystrokes, real muscle memory.'

// ------------------------------------------------------------- Markdown ---

export function cheatsheetMarkdown(): string {
  const lines: string[] = []
  lines.push('# VimLegends — Vim Cheatsheet', '', `> ${TAGLINE}`, '', `_${SITE}_`, '')
  for (const s of cheatsheetSections()) {
    lines.push(`## World ${s.tier} · ${s.name}`, `_${s.subtitle}_`, '')
    for (const g of s.groups) {
      lines.push(`**${g.label}**`, '', '| Keys | What it does |', '| --- | --- |')
      for (const c of g.commands) lines.push(`| \`${c.keys}\` | ${c.label} |`)
      lines.push('')
    }
  }
  lines.push('---', '', `${COMMANDS.length} commands across ${cheatsheetSections().length} worlds · generated by VimLegends.`)
  return lines.join('\n')
}

// ----------------------------------------------------------------- HTML ---

const esc = (s: string) => s.replace(/[&<>"]/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[ch]!)

/** A standalone, print-optimized HTML page (inline CSS, no external assets). */
export function cheatsheetHtml(): string {
  const sections = cheatsheetSections()
  const cards = sections
    .map((s) => {
      const groups = s.groups
        .map(
          (g) => `
          <div class="grp">
            <h3>${esc(g.label)}</h3>
            ${g.commands
              .map((c) => `<div class="row"><kbd>${esc(c.keys)}</kbd><span>${esc(c.label)}</span></div>`)
              .join('')}
          </div>`,
        )
        .join('')
      return `
      <section class="card" style="--accent:${s.accent}">
        <header><span class="tier">World ${s.tier}</span><h2>${esc(s.name)}</h2><p>${esc(s.subtitle)}</p></header>
        ${groups}
      </section>`
    })
    .join('')

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VimLegends — Vim Cheatsheet</title>
<style>
  :root{--bg:#0b0d14;--panel:#121620;--panel2:#1a2030;--border:#2a3044;--ink:#e2e6f0;--dim:#8b93a7;--term:#7c6bff}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);font-family:'Space Grotesk',system-ui,-apple-system,sans-serif;line-height:1.4}
  .wrap{max-width:1100px;margin:0 auto;padding:32px 20px 56px}
  .top{text-align:center;margin-bottom:28px}
  .top h1{font-size:38px;margin:0;letter-spacing:-.5px;background:linear-gradient(135deg,#7c6bff,#4cc9f0,#ff6ac1);-webkit-background-clip:text;background-clip:text;color:transparent}
  .top p{color:var(--dim);margin:6px 0 0}
  .top a{color:var(--term);text-decoration:none}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px}
  .card{background:var(--panel);border:1px solid var(--border);border-top:3px solid var(--accent);border-radius:12px;padding:16px 18px;break-inside:avoid}
  .card>header{margin-bottom:10px}
  .card .tier{font-size:11px;text-transform:uppercase;letter-spacing:.14em;color:var(--dim)}
  .card h2{margin:2px 0 0;font-size:22px;color:var(--accent)}
  .card header p{margin:2px 0 0;font-size:13px;color:var(--dim)}
  .grp{margin-top:12px}
  .grp h3{margin:0 0 6px;font-size:11px;text-transform:uppercase;letter-spacing:.14em;color:var(--dim);border-bottom:1px solid var(--border);padding-bottom:4px}
  .row{display:flex;align-items:baseline;gap:10px;padding:3px 0}
  .row kbd{font-family:'JetBrains Mono',ui-monospace,monospace;font-size:12.5px;background:var(--panel2);border:1px solid var(--border);border-radius:6px;padding:2px 7px;white-space:nowrap;color:var(--ink);min-width:74px;text-align:center}
  .row span{font-size:13.5px;color:var(--ink)}
  footer{text-align:center;color:var(--dim);font-size:12px;margin-top:32px}
  @media print{
    :root{--bg:#fff;--panel:#fff;--panel2:#f2f3f7;--border:#c9cede;--ink:#14161f;--dim:#5b6376}
    body{background:#fff}
    .top h1{color:#4b3fd6;-webkit-text-fill-color:#4b3fd6}
    .grid{grid-template-columns:repeat(2,1fr)}
    .card{box-shadow:none}
    a[href]:after{content:""}
  }
</style></head>
<body><div class="wrap">
  <div class="top">
    <h1>:VimLegends — Vim Cheatsheet</h1>
    <p>${esc(TAGLINE)}</p>
    <p><a href="${SITE}">${SITE}</a></p>
  </div>
  <div class="grid">${cards}</div>
  <footer>${COMMANDS.length} commands · ${sections.length} worlds · generated by VimLegends</footer>
</div></body></html>`
}

// ------------------------------------------------------------- download ---

/** Trigger a browser download of an in-memory string as a file. */
export function downloadTextFile(filename: string, mime: string, content: string): void {
  if (typeof document === 'undefined' || typeof URL.createObjectURL !== 'function') return
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.rel = 'noopener'
  document.body.appendChild(a)
  a.click()
  a.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 2000)
}

export type CheatFormat = 'md' | 'html'

export function downloadCheatsheet(format: CheatFormat): void {
  if (format === 'md') {
    downloadTextFile('vimlegends-cheatsheet.md', 'text/markdown;charset=utf-8', cheatsheetMarkdown())
  } else {
    downloadTextFile('vimlegends-cheatsheet.html', 'text/html;charset=utf-8', cheatsheetHtml())
  }
}

/** Open the printable HTML in a new tab and invoke the print dialog. */
export function printCheatsheet(): void {
  if (typeof window === 'undefined') return
  const w = window.open('', '_blank', 'noopener,noreferrer')
  if (!w) {
    // Popup blocked — fall back to a straight HTML download the user can print.
    downloadCheatsheet('html')
    return
  }
  w.document.open()
  w.document.write(cheatsheetHtml())
  w.document.close()
  w.focus()
  // Give the new document a tick to lay out before printing.
  window.setTimeout(() => w.print(), 350)
}
